- hosts: master
  become: no
  tasks:
  - name: Add Rancher helm repository
    community.kubernetes.helm_repository:
      name: rancher-latest
      repo_url: https://releases.rancher.com/server-charts/latest

  - name: cert-manager - install CustomResourceDefinition resources
    shell: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml

  - name: cert-manager - add Jetstack Helm repository
    community.kubernetes.helm_repository:
      name: jetstack
      repo_url: https://charts.jetstack.io

  - name: cert-manager - install via Helm
    community.kubernetes.helm:
      wait: yes
      name: cert-manager
      namespace: cert-manager
      create_namespace: yes
      chart_ref: jetstack/cert-manager
      chart_version: 1.0.4

  - name: Deploy Rancher via Helm
    community.kubernetes.helm:
      name: rancher
      namespace: cattle-system
      create_namespace: yes
      chart_ref: rancher-latest/rancher
      values: "{{ lookup('template', 'config.yml') | from_yaml }}"
