- hosts: master
  become: no
  tasks:
  
  - name: Helm - install Ingress for webapp
    community.kubernetes.helm:
      wait: yes
      name: ingress-public
      namespace: ingress-public
      create_namespace: true
      chart_ref: ingress-nginx/ingress-nginx
      values:
        controller:
          ingressClass: public
  
  - name: Add Bitnami Helm repository
    community.kubernetes.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami
  
  - name: Install nginx via Helm
    community.kubernetes.helm:
      name: nginx
      chart_ref: bitnami/nginx
      namespace: nginx-test
      create_namespace: true
      values:
        ingress:
          enabled: true
          hostname: www.projet.cloud
          annotations:
            kubernetes.io/ingress.class: public

