- hosts: master
  become: no
  tasks:

#    - name: Add Rook repository
#      community.kubernetes.helm_repository:
#        name: rook-release
#        repo_url: https://charts.rook.io/release

#    - name: Install Rook-Ceph storage platform via Helm
#      community.kubernetes.helm:
#        name: rook-ceph
#        namespace: rook-ceph
#        create_namespace: true
#        chart_ref: rook-release/rook-ceph

#    - name: Create StorageClass for Harbor persistent storage
#      community.kubernetes.k8s:
#        definition: "{{ lookup('template', 'storageClass.yml') | from_yaml  }}"

    - name: Add Harbor repository
      community.kubernetes.helm_repository:
        name: harbor
        repo_url: https://helm.goharbor.io

    - name: Deploy Harbor container registry via Helm
      community.kubernetes.helm:
        name: harbor
        namespace: harbor-system
        create_namespace: true
        chart_ref: harbor/harbor
        values: "{{ lookup('template', 'harbor-config.yml') | from_yaml }}"
