- hosts: master
  become: yes
  gather_facts: false
  tasks:

  - name: generate join command
    shell: kubeadm token create --print-join-command
    register: join_command
  
  - name: set fact join command
    set_fact:
      join_command: "{{ join_command.stdout_lines|last }}"

- hosts: workers
  become: yes
  tasks:
    - name: kubeadm reset workers
      shell: kubeadm reset -f

    - name: join cluster
      shell: "{{ hostvars['master'].join_command }}"
